TERMUX_PKG_HOMEPAGE="https://codeberg.org/derat/xsettingsd"
TERMUX_PKG_DESCRIPTION="Provides settings to X11 applications via the XSETTINGS specification"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_LICENSE_FILE="LICENSE"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.0.4"
TERMUX_PKG_SRCURL="https://codeberg.org/derat/xsettingsd/archive/v${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=3a36ce39bfadb3804c76b986c0654d211bb70ba85f900742dd3bb3403d17175f
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++, libx11"
