TERMUX_PKG_HOMEPAGE=https://www.harding.motd.ca/autossh/
TERMUX_PKG_DESCRIPTION="Automatically restart SSH sessions and tunnels"
TERMUX_PKG_LICENSE="BSD"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.4g
TERMUX_PKG_REVISION=4
TERMUX_PKG_SRCURL=https://www.harding.motd.ca/autossh/autossh-${TERMUX_PKG_VERSION}.tgz
TERMUX_PKG_SHA256=5fc3cee3361ca1615af862364c480593171d0c54ec156de79fc421e31ae21277
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="openssh | dropbear"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="--mandir=$TERMUX_PREFIX/share/man ac_cv_path_ssh=$TERMUX_PREFIX/bin/ssh"
