name: Build random unbuilt package

on:
  schedule:
    - cron: "0 * * * *" # Run once per hour
  workflow_dispatch:

permissions: {} # none

jobs:
  RandomName:
    permissions:
      contents: read
    if: github.repository == 'pelya/termux-packages'
    runs-on: ubuntu-slim
    outputs:
      PACKAGE_NAME: ${{ steps.GetName.outputs.PACKAGE_NAME }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get package name
        id: GetName
        run: |
          PACKAGE_NAME="$(scripts/bin/random-package-not-in-repo)"
          echo PACKAGE_NAME=$PACKAGE_NAME
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_OUTPUT

  Build:
    permissions:
      contents: read
    needs: RandomName
    name: Build ${{ needs.RandomName.outputs.PACKAGE_NAME }}
    if: ${{ needs.RandomName.outputs.PACKAGE_NAME != '' }} && github.repository == 'pelya/termux-packages'
    uses: pelya/termux-packages/.github/workflows/packages.yml@master
    with:
      packages: ${{ needs.RandomName.outputs.PACKAGE_NAME }}
    secrets:
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      DISTS_UPLOAD_TOKEN: ${{ secrets.DISTS_UPLOAD_TOKEN }}
        
